### ISSUE TITLE
训练mayapi的代码是哪一部分呢

### ISSUE THREAD

**Issue by lanmao123** [Yangyi-Chen/MAYA#1]
您好,训练mayapi的代码是哪一部分呢,论文没看懂

**Comment by LTEnjoy** [comment]
你好，我刚刚把训练mayapi的代码传上来了。rl_training.py文件是mayapi的训练代码。

**Comment by lanmao123** [comment]
> 你好，我刚刚把训练mayapi的代码传上来了。rl_training.py文件是mayapi的训练代码。

感谢,还有个问题,我看文中用的是dagger方法来不断生成训练数据,训练集(xx_correct_train_rl.tsv)是不公开的吗,还是库中哪个代码生成的?

**Comment by LTEnjoy** [comment]
初始训练集是基于victim model的分类正确程度提前生成好的，因为不同的victim model生成的训练集不同，所以我们并没有公开数据集。如果您需要我们的victim model下的训练集，可以告诉我，我将文件发送至您的邮箱。

**Comment by lanmao123** [comment]
> 初始训练集是基于victim model的分类正确程度提前生成好的，因为不同的victim model生成的训练集不同，所以我们并没有公开数据集。如果您需要我们的victim model下的训练集，可以告诉我，我将文件发送至您的邮箱。

感谢,bluecat970519@gmail.com,研读论文还有一些问题,请指教一下

**Comment by lanmao123** [comment]
> > 初始训练集是基于victim model的分类正确程度提前生成好的，因为不同的victim model生成的训练集不同，所以我们并没有公开数据集。如果您需要我们的victim model下的训练集，可以告诉我，我将文件发送至您的邮箱。
> 
> 感谢,[bluecat970519@gmail.com](mailto:bluecat970519@gmail.com),研读论文还有一些问题,请指教一下

bert sst2 (t5 or baidu) ;或者您直接把3.2.2 Training Process那部分代码发我研读一下,谢谢您了

**Comment by LTEnjoy** [comment]
训练的代码就是那个rl_training.py文件。bert sst2的训练集我已经发给您了
